web:
  restart: always
  image: drupal:7
  ports:
    - "8080:80"
  volumes:
    - ../config/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
    - ../config/apache:/etc/apache2/sites-enabled
    - ../../Sites/Drupal/themes:/var/www/html/sites/all/themes # Drupal sites folder
  links:
    - db

db:
  extends:
    file: ../docker-root.yml
    service: db

adminer:
  extends:
    file: ../docker-root.yml
    service: adminer
  links:
    - db
