web:
  build: .
  dockerfile: Dockerfile
  restart: always
  # image: php:7.0-apache
  ports:
    - "8080:80"
  volumes:
    - ../config/php/30-custom.ini:/usr/local/etc/php/conf.d/30-custom.ini
    - ../config/apache:/etc/apache2/sites-enabled
    - ../../Sites:/var/www/html
  links:
    - db

db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_USER=admin"
    - "MYSQL_PASSWORD=admin"
    - "MYSQL_DATABASE=photofolio"
